version: "3"
services:
  fhir-api:
    image: "mcr.microsoft.com/healthcareapis/r4-fhir-server"
    environment:
      FHIRServer__Security__Enabled: "false"
      SqlServer__ConnectionString: "Server=tcp:sql,1433;Initial Catalog=FHIR;Persist Security Info=False;User ID=SA;Password=${SAPASSWORD};MultipleActiveResultSets=False;Connection Timeout=30;"
      SqlServer__AllowDatabaseCreation: "true"
      SqlServer__Initialize: "true"
      SqlServer__SchemaOptions__AutomaticUpdatesEnabled: "true"
      DataStore: "SqlServer"
    ports:     
      - "8080:8080"
    depends_on:
      - sql
    command: ["./wait-for-sql.sh", "sql:1433", "--", "dotnet", "Microsoft.Health.Fhir.Web.dll"]
  sql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: ${SAPASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd","-U SA -P ${SAPASSWORD} -Q 'SELECT * FROM INFORMATION_SCHEMA.TABLES'"]
        interval: 10s
        timeout: 10s
        retries: 6